# Databricks + LangGraph/LangChain anchoring, and the final module order.
MODULES = [
 ("foundations", "AI & ML foundations", "How models learn from data, and how you know whether they're any good.",
  ["split_by_key", "precision_recall", "best_threshold"]),
 ("experiments", "Experiment design with MLflow", "Runs, grids, fair comparisons and decisions you can defend.",
  ["best_run", "param_grid", "cv_folds", "clear_winner"]),
 ("llm-apps", "Building with LLMs", "Prompts, parsing replies, batching and retries, with LangChain and Databricks model endpoints.",
  ["fill_template", "extract_code_block", "batch_items", "backoff_delays"]),
 ("rag", "RAG with Vector Search", "Chunking, indexing and retrieval, then measuring which settings actually work.",
  ["chunk_text", "dedupe_chunks", "retrieve", "recall_at_k", "pick_config"]),
 ("agents", "Agents with LangGraph", "The agent loop, memory, tools from Unity Catalog, and scoring the result.",
  ["run_agent", "trim_history", "tool_schema", "tool_pairs", "agent_scorecard"]),
 ("evals", "Evals", "Measuring whether a change made your AI better or worse.",
  ["exact_match", "first_bad_version"]),
 ("models", "Choosing a model", "Quality, cost and latency, and which option pays for itself.",
  ["percentile", "pareto_models", "better_option"]),
 ("tracing", "Tracing and AgentOps", "Traces that answer your questions, slow steps and runaway agents.",
  ["summarize_by_tag", "slowest_chain", "detect_loop"]),
 ("llmops", "LLMOps", "Cost and caching in production.",
  ["token_cost", "cache_hits"]),
 ("shipping", "Shipping models and agents", "Registering, promoting and canarying on Databricks.",
  ["promote_model", "route_request"]),
 ("platform", "ML platform on Azure Databricks", "The Terraform and Spacelift work behind the platform.",
  ["summarize_plan", "find_replacements", "guard_destroys", "lock_info", "missing_tags", "grants_to_revoke", "count_shift", "overlapping_subnets", "apply_order"]),
]
LIFECYCLE = [
 ("Frame", "Decide the question, the metric and what success is worth.", ["foundations"]),
 ("Design", "Plan the runs: what you vary, what you hold fixed, what it costs.", ["experiments"]),
 ("Build and trace", "Build with LangGraph and Databricks, traced from the first line.", ["llm-apps", "rag", "agents"]),
 ("Evaluate", "Score runs on the same eval set; compare quality, cost and latency.", ["evals", "models"]),
 ("Ship", "Register, promote and canary with a rule you wrote down first.", ["shipping", "platform"]),
 ("Monitor", "Watch real traffic in traces and feed failures back into evals.", ["tracing", "llmops"]),
]

L = {}
def lesson(id, title, learn, example, check, angle):
    L[id] = dict(title=title, learn=learn, example=example, check=check, angle=angle)

lesson("tool_schema", "Tools from Unity Catalog",
 ["An agent's tools are described to the model as a **name**, a **description** and **parameters**. The model picks a tool by reading those descriptions, so they are part of your prompt.",
  "On Databricks, a common pattern is to write tools as **Unity Catalog functions**: governed, permissioned and reusable. `UCFunctionToolkit` turns them into LangChain tools, using the function and parameter comments as descriptions."],
 ("A tool as the model sees it", "{\"type\": \"function\", \"function\": {\n  \"name\": \"lookup_order\",\n  \"description\": \"Look up an order's status and delivery date\",\n  \"parameters\": {\"type\": \"object\",\n    \"properties\": {\"order_id\": {\"type\": \"string\", \"description\": \"The order number, like A-1042\"}},\n    \"required\": [\"order_id\"]}}}"),
 ("Your agent keeps calling `get_data` when it should call `lookup_order`. What's the cheapest fix to try first?",
  ["A bigger model", "Clearer function and parameter comments", "More tools"], 1,
  "The model chooses from the descriptions. Vague comments cause wrong picks."),
 ("Building nested structures", "A lookup table for the types, then one step per parameter to fill the properties. Interviews test this as \"transform this data into that shape\".",
  "\"I map each parameter through a type lookup table into the properties dict, collect the required names in order, and wrap it in the schema.\"", None))

lesson("route_request", "Canary releases",
 ["Never switch all traffic to a new agent at once. Send a small share (say 10%) to the new version, compare its traces and evals with the old one, then move the split.",
  "A Databricks serving endpoint can serve several versions and split traffic between them by percentage. Rolling back is just setting the new version to 0%."],
 ("A 90/10 split", "routes = [\n  {\"served_entity_name\": \"support_agent-3\", \"traffic_percentage\": 90},\n  {\"served_entity_name\": \"support_agent-4\", \"traffic_percentage\": 10},\n]"),
 ("The canary's error rate doubles in the first hour. What do you do?",
  ["Wait a week for more data", "Move its traffic back to 0% and look at its traces", "Switch everyone to it"], 1,
  "That's what a stop rule is for. Roll back first, then investigate."),
 ("Running total", "Walk the routes adding percentages and stop at the first total that passes the bucket. One walk through the routes.",
  "\"I bucket the request id into 0–99 and walk the routes with a running total; the first route whose total exceeds the bucket wins.\"", None))

# One "In your stack" snippet per lesson: (caption, code). Platform lessons are Terraform and have none.
STACK = {
 "split_by_key": ("MLflow: record which data trained the model", "with mlflow.start_run(run_name=\"churn-split-by-user\"):\n    mlflow.log_params({\"split\": \"by_user\", \"test_users\": len(test_users)})\n    mlflow.log_input(mlflow.data.from_pandas(train_df, name=\"train\"), context=\"training\")"),
 "precision_recall": ("MLflow: log both numbers on every run", "mlflow.sklearn.autolog()   # params, metrics and the model on every fit\nmlflow.log_metrics({\"precision\": 0.67, \"recall\": 0.67})"),
 "best_threshold": ("MLflow: the threshold is a parameter", "with mlflow.start_run(run_name=\"threshold-0.65\"):\n    mlflow.log_param(\"threshold\", 0.65)\n    mlflow.log_metric(\"val_accuracy\", 1.0)"),
 "best_run": ("MLflow: find the best run within budget", "runs = mlflow.search_runs(\n    experiment_names=[\"/Shared/support-bot-rag\"],\n    filter_string=\"metrics.cost_per_1k < 2.0\",\n    order_by=[\"metrics.quality DESC\"],\n)\nbest = runs.iloc[0]"),
 "param_grid": ("MLflow: one run per combination", "for config in grid:\n    with mlflow.start_run(run_name=f\"cs{config['chunk_size']}-k{config['k']}\"):\n        mlflow.log_params(config)\n        mlflow.log_metrics(run_eval(config))"),
 "cv_folds": ("scikit-learn with MLflow autologging", "mlflow.sklearn.autolog()\nwith mlflow.start_run(run_name=\"logreg-5fold\"):\n    scores = cross_val_score(model, X, y, cv=5, scoring=\"f1\")\n    mlflow.log_metrics({\"f1_mean\": scores.mean(), \"f1_min\": scores.min()})"),
 "clear_winner": ("MLflow: repeat runs as nested runs", "with mlflow.start_run(run_name=\"prompt_b\"):\n    for seed in [1, 2, 3]:\n        with mlflow.start_run(run_name=f\"seed-{seed}\", nested=True):\n            mlflow.log_metric(\"quality\", evaluate(prompt_b, seed=seed))"),
 "fill_template": ("LangChain: literal braces are doubled", "from langchain_core.prompts import ChatPromptTemplate\nprompt = ChatPromptTemplate.from_messages([\n    (\"system\", 'Reply as JSON like {{\"ok\": true}}'),\n    (\"human\", \"{question}\"),\n])"),
 "extract_code_block": ("LangChain: ask for structured output instead", "from pydantic import BaseModel\nfrom databricks_langchain import ChatDatabricks\n\nclass Ticket(BaseModel):\n    category: str\n    urgent: bool\n\nllm = ChatDatabricks(endpoint=ENDPOINT).with_structured_output(Ticket)"),
 "batch_items": ("Databricks: batch inference over a table with ai_query", "SELECT ticket_id,\n       ai_query('databricks-gte-large-en', text) AS embedding\nFROM main.support.tickets"),
 "backoff_delays": ("LangChain: retries with growing waits", "llm = ChatDatabricks(endpoint=ENDPOINT).with_retry(\n    stop_after_attempt=4,\n    wait_exponential_jitter=True,\n)\n# A 429 from a Databricks endpoint usually means an AI Gateway rate limit."),
 "chunk_text": ("Databricks Vector Search: index a table of chunks", "vsc.create_delta_sync_index(\n    endpoint_name=\"vs-endpoint\", index_name=\"main.support.docs_index\",\n    source_table_name=\"main.support.doc_chunks\", pipeline_type=\"TRIGGERED\",\n    primary_key=\"chunk_id\", embedding_source_column=\"text\",\n    embedding_model_endpoint_name=\"databricks-gte-large-en\",\n)"),
 "dedupe_chunks": ("Databricks SQL: keep one chunk per cleaned text", "CREATE OR REPLACE TABLE main.support.doc_chunks_clean AS\nSELECT * FROM main.support.doc_chunks\nQUALIFY row_number() OVER (\n  PARTITION BY lower(regexp_replace(text, '\\\\s+', ' ')) ORDER BY chunk_id) = 1"),
 "retrieve": ("Databricks Vector Search: hybrid search", "from databricks.vector_search.client import VectorSearchClient\nindex = VectorSearchClient().get_index(endpoint_name=\"vs-endpoint\", index_name=\"main.support.docs_index\")\nresults = index.similarity_search(\n    query_text=question, columns=[\"chunk_id\", \"text\"],\n    query_type=\"HYBRID\", num_results=5,\n)"),
 "recall_at_k": ("MLflow: a recall@5 scorer", "from mlflow.genai.scorers import scorer\n\n@scorer\ndef recall_at_5(outputs, expectations):\n    found = set(outputs[\"doc_ids\"][:5])\n    wanted = set(expectations[\"relevant_ids\"])\n    return len(found & wanted) / len(wanted) if wanted else 0.0"),
 "pick_config": ("MLflow: one evaluated run per config", "for chunk_size, k in [(256, 3), (512, 5), (1024, 10)]:\n    with mlflow.start_run(run_name=f\"cs{chunk_size}-k{k}\"):\n        mlflow.log_params({\"chunk_size\": chunk_size, \"k\": k})\n        mlflow.genai.evaluate(data=eval_set, predict_fn=make_app(chunk_size, k),\n                              scorers=[RetrievalGroundedness(), RelevanceToQuery()])"),
 "run_agent": ("LangGraph: a hard step limit", "graph = builder.compile()\ngraph.invoke({\"messages\": messages}, config={\"recursion_limit\": 10})\n# Raises GraphRecursionError instead of looping forever."),
 "trim_history": ("LangChain: trim_messages", "from langchain_core.messages import trim_messages\ntrimmed = trim_messages(\n    messages, max_tokens=2000, strategy=\"last\",\n    token_counter=llm, include_system=True, start_on=\"human\",\n)"),
 "tool_schema": ("databricks_langchain: Unity Catalog functions as tools", "from databricks_langchain import ChatDatabricks, UCFunctionToolkit\ntools = UCFunctionToolkit(function_names=[\"main.support.lookup_order\"]).tools\nllm = ChatDatabricks(endpoint=ENDPOINT).bind_tools(tools)"),
 "tool_pairs": ("LangGraph: ToolNode answers every tool call", "from langgraph.prebuilt import ToolNode\nbuilder.add_node(\"tools\", ToolNode(tools))\n# One ToolMessage per call, with the matching tool_call_id, errors included."),
 "agent_scorecard": ("MLflow: an LLM judge for task success", "from mlflow.genai.judges import make_judge\ntask_done = make_judge(\n    name=\"task_success\",\n    instructions=\"Did the agent complete the user's task?\\nUser: {{ inputs }}\\nAgent: {{ outputs }}\\nAnswer yes or no.\",\n)\nmlflow.genai.evaluate(data=tasks, predict_fn=run_agent, scorers=[task_done])"),
 "exact_match": ("MLflow: Correctness with expected answers", "from mlflow.genai.scorers import Correctness\ndata = [{\"inputs\": {\"question\": \"Capital of France?\"},\n         \"expectations\": {\"expected_response\": \"Paris\"}}]\nmlflow.genai.evaluate(data=data, predict_fn=my_app, scorers=[Correctness()])"),
 "first_bad_version": ("MLflow: one named run per version", "with mlflow.start_run(run_name=\"prompt-v17\"):\n    mlflow.set_tag(\"prompt_version\", \"17\")\n    mlflow.genai.evaluate(data=eval_set, predict_fn=app_v17, scorers=scorers)"),
 "percentile": ("MLflow: find slow traces", "slow = mlflow.search_traces(\n    filter_string=\"attributes.execution_time_ms > 5000\", max_results=100,\n)"),
 "pareto_models": ("MLflow: one run per candidate endpoint", "for endpoint in candidates:   # Foundation Model API endpoints in your workspace\n    with mlflow.start_run(run_name=endpoint):\n        mlflow.log_param(\"endpoint\", endpoint)\n        mlflow.genai.evaluate(data=eval_set, predict_fn=make_app(endpoint), scorers=[Correctness()])"),
 "better_option": ("MLflow: log the decision with its numbers", "with mlflow.start_run(run_name=\"decision-oct\"):\n    mlflow.log_params({\"volume\": 10_000, \"value_per_success\": 4.0})\n    mlflow.log_metric(\"net_monthly_value\", 35_700)\n    mlflow.set_tag(\"decision\", \"ship smart-model\")"),
 "summarize_by_tag": ("MLflow tracing a LangGraph app, with tags", "mlflow.langchain.autolog()   # every LangGraph run becomes a trace\n\n@mlflow.trace\ndef answer(question):\n    mlflow.update_current_trace(tags={\"config\": \"cs512-k5\", \"model\": ENDPOINT})\n    return graph.invoke({\"messages\": [(\"user\", question)]})"),
 "slowest_chain": ("MLflow: find the slowest model call", "from mlflow.entities import SpanType\nspans = trace.search_spans(span_type=SpanType.CHAT_MODEL)\nslowest = max(spans, key=lambda s: s.end_time_ns - s.start_time_ns)"),
 "detect_loop": ("LangGraph: stop on a repeated call", "def route(state):\n    calls = [str(m.tool_calls) for m in state[\"messages\"] if getattr(m, \"tool_calls\", None)]\n    if len(calls) >= 3 and len(set(calls[-3:])) == 1:\n        return \"stop\"\n    return \"tools\" if state[\"messages\"][-1].tool_calls else \"end\""),
 "token_cost": ("Databricks: tokens per endpoint from AI Gateway usage tracking", "SELECT served_entity_id,\n       sum(input_token_count)  AS input_tokens,\n       sum(output_token_count) AS output_tokens\nFROM system.serving.endpoint_usage\nWHERE request_time >= current_date() - INTERVAL 7 DAYS\nGROUP BY served_entity_id"),
 "cache_hits": ("LangChain: an LLM cache", "from langchain_core.globals import set_llm_cache\nfrom langchain_core.caches import InMemoryCache\nset_llm_cache(InMemoryCache())"),
 "promote_model": ("Databricks: move the champion alias in Unity Catalog", "from mlflow import MlflowClient\nMlflowClient(registry_uri=\"databricks-uc\").set_registered_model_alias(\n    \"main.support.support_agent\", \"champion\", version=4)"),
 "route_request": ("Databricks: a 90/10 split on a serving endpoint", "deploy = mlflow.deployments.get_deploy_client(\"databricks\")\ndeploy.update_endpoint(endpoint=\"support-agent\", config={\n    \"served_entities\": [...],   # versions 3 and 4\n    \"traffic_config\": {\"routes\": [\n        {\"served_model_name\": \"support_agent-3\", \"traffic_percentage\": 90},\n        {\"served_model_name\": \"support_agent-4\", \"traffic_percentage\": 10}]},\n})"),
}
