# Plain-language replacements for the interview-angle text (no Big-O notation; see the user's plain-language preference).
ANGLE = {
 "split_by_key": ("You check every row against a set of test values. A set answers \"is this in here?\" in one step however big it is, so the whole split is a single walk through the rows. Checking a list instead means scanning the list for every row, which gets slow fast.",
   "\"I put the test keys in a set so each check is instant, which makes the split one pass over the rows.\""),
 "precision_recall": ("Each pair goes into one bucket and gets counted, in one walk through the lists, with just three counters. Interviewers like to hear that you guard against dividing by zero.",
   "\"One pass to count true positives, false positives and false negatives, then two divisions, each guarded in case the bottom number is zero.\""),
 "best_threshold": ("Trying every threshold against every example checks every pair, which gets slow on big data: 10,000 examples means 100 million checks. Sorting the examples by score first lets you move the threshold one example at a time and update the count as you go. The same sort-then-sweep idea solves Merge Intervals.",
   "\"Trying every pair is slow on big data. If I sort by score first, each step changes one prediction, so I update the accuracy as I go instead of recounting.\""),
 "fill_template": ("One replace per value you were given. The point is correctness: only touch what you own. Matching opening and closing markers properly is the idea behind Valid Parentheses.",
   "\"I loop over the values I was given and replace exactly those placeholders, so any other braces in the text survive.\""),
 "extract_code_block": ("`find` reads the text once. What interviewers look for is handling the case where the marker isn't there, not just the happy path.",
   "\"I find the fence, slice between the markers, and fall back to the whole trimmed reply when there's no fence.\""),
 "batch_items": ("`range(0, len(items), size)` visits each starting point once, and every item lands in exactly one slice, so it's one walk through the list.",
   "\"I step through the list in jumps of the batch size and slice each batch; the last slice is just shorter, so nothing is dropped.\""),
 "backoff_delays": ("Every wait is worked out from the one before: double it, then cap it. That \"build the next answer from the last one\" idea is the heart of Climbing Stairs. One step per retry.",
   "\"I keep one running value, double it each retry and cap it with min, so I never store more than I need.\""),
 "chunk_text": ("A fixed-size window moves along the text in steps, so each part of the text is read only a couple of times. Longest Substring Without Repeating Characters uses a window that grows and shrinks instead.",
   "\"I slide a fixed window forward by size minus overlap, and stop once a window reaches the end so the last chunk isn't repeated.\""),
 "dedupe_chunks": ("Turn each item into a key that comes out the same exactly when two items should count as the same, and keep a set of keys you've seen. One walk through the chunks. Group Anagrams is the same trick, with sorted letters as the key.",
   "\"I turn each chunk into a cleaned-up key and keep a set of keys I've seen, so the first copy survives and the rest are dropped in one pass.\""),
 "retrieve": ("Score every document once, then sort. When there are millions of documents and you only want the top few, a heap (`heapq.nlargest`) keeps just those few as it goes, which is much faster than sorting everything.",
   "\"Sorting everything works. A heap that keeps only the best k as I go is much faster when there are millions of documents.\""),
 "run_agent": ("The loop runs at most max_steps times, and each step is one lookup. The interview point is the stopping rules: a final answer, the step limit, or the end of the plan.",
   "\"Every loop that depends on a model has a hard limit, and tool errors go back to the model as messages so it can recover.\""),
 "trim_history": ("Walk backwards once and stop at the first message that doesn't fit. Many \"budget\" problems, including two-pointer and sliding-window ones, use the same thinking.",
   "\"I keep the system message, then fill the rest of the budget from the newest message backwards and stop at the first that doesn't fit, so there are no gaps.\""),
 "tool_pairs": ("Open on a call, close on its result, and report anything left open or closed without being opened, in one walk through the messages. Valid Parentheses is the same idea with a stack, because brackets must close in order.",
   "\"I track open call ids and each result closes one. Whatever is still open at the end, or closed without being opened, is an error.\""),
 "exact_match": ("zip the two lists and compare each pair once. Check for the empty case before dividing.",
   "\"I clean both sides with the same function, compare pairs with zip, and return 0 for an empty set instead of dividing by zero.\""),
 "first_bad_version": ("Each check throws away half of what's left, so 1,000 versions take about 10 checks and a million take about 20. The classic bug is the boundary: whether you move to the middle or one past it.",
   "\"The passing versions all come before the failing ones, so I check the middle and throw away half each time. That needs only a handful of evals.\""),
 "token_cost": ("One walk through the calls, adding each cost into a dict keyed by model. Group Anagrams has the same group-by-key shape.",
   "\"I add up into a dict keyed by model in one pass, and round only at the end so rounding errors don't pile up.\""),
 "cache_hits": ("A dict finds things instantly, and a linked list (or Python's OrderedDict) remembers which item was used least recently. Together, every lookup and every eviction is instant. \"Design an LRU cache\" is itself a very common interview question.",
   "\"A dict for instant lookups plus a linked list for the order of use, so reading and adding are both instant.\""),
 "promote_model": ("One walk through the versions, keeping the best candidate so far, with a clear rule for ties. Maximum Subarray uses the same keep-the-best-so-far bookkeeping.",
   "\"One pass with a running best. Only candidates that clear the minimum gain can replace it, and ties go to the earlier version.\""),
 "summarize_plan": ("Three counters and one walk through `resource_changes`.",
   "\"I walk the resource changes once and count by action, treating a replacement as both an add and a destroy, the way Terraform does.\""),
 "find_replacements": ("Keep the entries that match a rule, in order, in one walk.",
   "\"I keep the resource changes whose actions contain both delete and create, which is how a replacement shows up in plan JSON.\""),
 "guard_destroys": ("Turn the protected types into a set so each check is instant, then one walk through the plan.",
   "\"I put the protected types in a set and check the plan once.\""),
 "lock_info": ("One walk through the lines, splitting each one on the first colon only.",
   "\"I scan once, start collecting at the Lock Info heading, and split each line on the first colon so the timestamp stays whole.\""),
 "missing_tags": ("One walk through the plan; each missing-tag check is an instant dict lookup.",
   "\"I only check resources that support tags, treat null as no tags, and return a dict from address to the missing keys.\""),
 "grants_to_revoke": ("For each principal, take away the privileges that are in code from the ones that are live. What's left is a set difference.",
   "\"For each principal I take the live privileges minus the ones in code; whatever is left is what an authoritative apply will remove.\""),
 "count_shift": ("Walk both lists side by side, up to the longer one.",
   "\"I compare position by position; a different name at the same position is a replacement, which is why keys beat positions.\""),
 "overlapping_subnets": ("Turn each CIDR into a start number and an end number; two ranges overlap when each starts before the other ends. Checking every pair is fine for a handful of subnets. With many ranges, sort them by start and sweep once, like Merge Intervals.",
   "\"I turn each CIDR into a numeric range. Sorted by start, an overlap is any range that starts before the previous one ends.\""),
 "apply_order": ("Count how many things each resource is still waiting for, start with the ones waiting for nothing, and each time one finishes, tell the ones waiting on it. This is called a topological sort. Number of Islands uses the same build-the-graph-then-walk-it thinking.",
   "\"I count what each resource is waiting for and keep a list of the ready ones. If some never become ready, there's a cycle.\""),
 "slowest_chain": ("Build a parent-to-children map in one walk, then follow one path down the tree. Number of Islands also builds the structure first and then walks it.",
   "\"I group spans by parent in one pass, then keep stepping into the slowest child until there are none.\""),
 "detect_loop": ("One walk, counting the current run of identical calls and starting again at 1 when the call changes.",
   "\"One pass with a counter for the current run of identical calls, reset whenever the call changes.\""),
}
# targeted fixes inside the 11 new problems (prompt / target / learn.why)
NEW_FIX = {
 "best_threshold": {"why": "Trying every threshold and checking every example means checking every pair, which slows down a lot on big data. Sorting by score first lets you move the threshold one example at a time and keep a running count."},
 "tool_pairs": {"why": "One walk through the messages. Removing from a list means searching it, which is fine for a handful of open calls; a set would make it instant."},
 "first_bad_version": {"target": "about 10 checks for 1,000 versions",
   "prompt_from": "so look at as few versions as possible: about log n of them, not all n.", "prompt_to": "so look at as few versions as possible: about 10 checks for 1,000 versions, not 1,000."},
 "cache_hits": {"target": "one walk through the prompts",
   "why": "One walk through the prompts. With a list, each lookup means scanning the cache; the interview version uses a dict plus a linked list, or Python's OrderedDict, to make every step instant."},
 "promote_model": {"why": "Two walks through the versions: one to find the champion's score, one to pick the best."},
}
# fixes to content carried over from the old page
OLD_FIX = [("Each pair is compared once. That's O(n²), which is fine for the handful of subnets a VNet has. Sorting by start first would make it O(n log n), like Merge Intervals.",
            "Each pair is compared once, which is fine for the handful of subnets a VNet has. With many ranges, sorting by start first lets you check each one only against its neighbour, like Merge Intervals.")]
CLASSIC_WHY = {
 "two_sum": "You look at each number once, and each dict check is instant, so the work grows only as fast as the list. The slow version tries every pair with a loop inside a loop.",
 "valid_parentheses": "You read each character once, and adding to or taking from the stack is instant. If the string is all openers, the stack holds all of them.",
 "binary_search": "Each step throws away half of what's left. A million items take only about 20 steps, because you can halve a million only about 20 times.",
 "climbing_stairs": "One walk from step 2 up to n, keeping only two numbers. The obvious recursive version works out the same steps over and over, which is why it times out on bigger inputs.",
 "longest_unique_substring": "Both edges of the window only move forward, so each character is visited only a couple of times. The dict holds at most one entry per different character.",
 "max_subarray": "One walk with two numbers to update. Checking every possible start and end would check every pair, which gets slow on long lists.",
 "merge_intervals": "Sorting is the slowest part; the sweep after it is a single walk. The result can hold every interval.",
 "group_anagrams": "Each word is sorted once to make its key, and every word is stored once in its group.",
 "num_islands": "Every cell is looked at only a couple of times: once by the scan, and at most once by a flood.",
}
